/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.java.tables.records;


import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.mcve.java.tables.Message;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessageRecord extends UpdatableRecordImpl<MessageRecord> implements Record13<Integer, OffsetDateTime, OffsetDateTime, Integer, String, String, Integer, Integer, Integer, Boolean, String, Boolean, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>mcve.message.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mcve.message.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mcve.message.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>mcve.message.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>mcve.message.event_time</code>.
     */
    public void setEventTime(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>mcve.message.event_time</code>.
     */
    public OffsetDateTime getEventTime() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>mcve.message.experience_id</code>.
     */
    public void setExperienceId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>mcve.message.experience_id</code>.
     */
    public Integer getExperienceId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>mcve.message.text_content</code>.
     */
    public void setTextContent(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mcve.message.text_content</code>.
     */
    public String getTextContent() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mcve.message.type</code>.
     */
    public void setType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mcve.message.type</code>.
     */
    public String getType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mcve.message.doctor_id</code>.
     */
    public void setDoctorId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>mcve.message.doctor_id</code>.
     */
    public Integer getDoctorId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>mcve.message.file_upload_id</code>.
     */
    public void setFileUploadId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>mcve.message.file_upload_id</code>.
     */
    public Integer getFileUploadId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>mcve.message.reply_message_id</code>.
     */
    public void setReplyMessageId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>mcve.message.reply_message_id</code>.
     */
    public Integer getReplyMessageId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>mcve.message.is_reply</code>.
     */
    public void setIsReply(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>mcve.message.is_reply</code>.
     */
    public Boolean getIsReply() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>mcve.message.sender_type</code>.
     */
    public void setSenderType(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>mcve.message.sender_type</code>.
     */
    public String getSenderType() {
        return (String) get(10);
    }

    /**
     * Setter for <code>mcve.message.is_automatic</code>.
     */
    public void setIsAutomatic(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>mcve.message.is_automatic</code>.
     */
    public Boolean getIsAutomatic() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>mcve.message.has_deleted_content</code>.
     */
    public void setHasDeletedContent(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>mcve.message.has_deleted_content</code>.
     */
    public Boolean getHasDeletedContent() {
        return (Boolean) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, OffsetDateTime, OffsetDateTime, Integer, String, String, Integer, Integer, Integer, Boolean, String, Boolean, Boolean> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Integer, OffsetDateTime, OffsetDateTime, Integer, String, String, Integer, Integer, Integer, Boolean, String, Boolean, Boolean> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Message.MESSAGE.ID;
    }

    @Override
    public Field<OffsetDateTime> field2() {
        return Message.MESSAGE.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return Message.MESSAGE.EVENT_TIME;
    }

    @Override
    public Field<Integer> field4() {
        return Message.MESSAGE.EXPERIENCE_ID;
    }

    @Override
    public Field<String> field5() {
        return Message.MESSAGE.TEXT_CONTENT;
    }

    @Override
    public Field<String> field6() {
        return Message.MESSAGE.TYPE;
    }

    @Override
    public Field<Integer> field7() {
        return Message.MESSAGE.DOCTOR_ID;
    }

    @Override
    public Field<Integer> field8() {
        return Message.MESSAGE.FILE_UPLOAD_ID;
    }

    @Override
    public Field<Integer> field9() {
        return Message.MESSAGE.REPLY_MESSAGE_ID;
    }

    @Override
    public Field<Boolean> field10() {
        return Message.MESSAGE.IS_REPLY;
    }

    @Override
    public Field<String> field11() {
        return Message.MESSAGE.SENDER_TYPE;
    }

    @Override
    public Field<Boolean> field12() {
        return Message.MESSAGE.IS_AUTOMATIC;
    }

    @Override
    public Field<Boolean> field13() {
        return Message.MESSAGE.HAS_DELETED_CONTENT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public OffsetDateTime component2() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component3() {
        return getEventTime();
    }

    @Override
    public Integer component4() {
        return getExperienceId();
    }

    @Override
    public String component5() {
        return getTextContent();
    }

    @Override
    public String component6() {
        return getType();
    }

    @Override
    public Integer component7() {
        return getDoctorId();
    }

    @Override
    public Integer component8() {
        return getFileUploadId();
    }

    @Override
    public Integer component9() {
        return getReplyMessageId();
    }

    @Override
    public Boolean component10() {
        return getIsReply();
    }

    @Override
    public String component11() {
        return getSenderType();
    }

    @Override
    public Boolean component12() {
        return getIsAutomatic();
    }

    @Override
    public Boolean component13() {
        return getHasDeletedContent();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public OffsetDateTime value2() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value3() {
        return getEventTime();
    }

    @Override
    public Integer value4() {
        return getExperienceId();
    }

    @Override
    public String value5() {
        return getTextContent();
    }

    @Override
    public String value6() {
        return getType();
    }

    @Override
    public Integer value7() {
        return getDoctorId();
    }

    @Override
    public Integer value8() {
        return getFileUploadId();
    }

    @Override
    public Integer value9() {
        return getReplyMessageId();
    }

    @Override
    public Boolean value10() {
        return getIsReply();
    }

    @Override
    public String value11() {
        return getSenderType();
    }

    @Override
    public Boolean value12() {
        return getIsAutomatic();
    }

    @Override
    public Boolean value13() {
        return getHasDeletedContent();
    }

    @Override
    public MessageRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MessageRecord value2(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public MessageRecord value3(OffsetDateTime value) {
        setEventTime(value);
        return this;
    }

    @Override
    public MessageRecord value4(Integer value) {
        setExperienceId(value);
        return this;
    }

    @Override
    public MessageRecord value5(String value) {
        setTextContent(value);
        return this;
    }

    @Override
    public MessageRecord value6(String value) {
        setType(value);
        return this;
    }

    @Override
    public MessageRecord value7(Integer value) {
        setDoctorId(value);
        return this;
    }

    @Override
    public MessageRecord value8(Integer value) {
        setFileUploadId(value);
        return this;
    }

    @Override
    public MessageRecord value9(Integer value) {
        setReplyMessageId(value);
        return this;
    }

    @Override
    public MessageRecord value10(Boolean value) {
        setIsReply(value);
        return this;
    }

    @Override
    public MessageRecord value11(String value) {
        setSenderType(value);
        return this;
    }

    @Override
    public MessageRecord value12(Boolean value) {
        setIsAutomatic(value);
        return this;
    }

    @Override
    public MessageRecord value13(Boolean value) {
        setHasDeletedContent(value);
        return this;
    }

    @Override
    public MessageRecord values(Integer value1, OffsetDateTime value2, OffsetDateTime value3, Integer value4, String value5, String value6, Integer value7, Integer value8, Integer value9, Boolean value10, String value11, Boolean value12, Boolean value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageRecord
     */
    public MessageRecord() {
        super(Message.MESSAGE);
    }

    /**
     * Create a detached, initialised MessageRecord
     */
    public MessageRecord(Integer id, OffsetDateTime createdAt, OffsetDateTime eventTime, Integer experienceId, String textContent, String type, Integer doctorId, Integer fileUploadId, Integer replyMessageId, Boolean isReply, String senderType, Boolean isAutomatic, Boolean hasDeletedContent) {
        super(Message.MESSAGE);

        setId(id);
        setCreatedAt(createdAt);
        setEventTime(eventTime);
        setExperienceId(experienceId);
        setTextContent(textContent);
        setType(type);
        setDoctorId(doctorId);
        setFileUploadId(fileUploadId);
        setReplyMessageId(replyMessageId);
        setIsReply(isReply);
        setSenderType(senderType);
        setIsAutomatic(isAutomatic);
        setHasDeletedContent(hasDeletedContent);
    }
}
