/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.java;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in mcve.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>mcve.experience_id_seq</code>
     */
    public static final Sequence<Integer> EXPERIENCE_ID_SEQ = Internal.createSequence("experience_id_seq", Mcve.MCVE, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>mcve.message_id_seq</code>
     */
    public static final Sequence<Integer> MESSAGE_ID_SEQ = Internal.createSequence("message_id_seq", Mcve.MCVE, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>mcve.test_id_seq</code>
     */
    public static final Sequence<Integer> TEST_ID_SEQ = Internal.createSequence("test_id_seq", Mcve.MCVE, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
